"""The ten pen-physics models, pinned against numbers the legacy code produced.

Two independent checks per formula, because one alone is weak:

1. **Legacy-produced literals.** ``_LEGACY_SEGMENT`` was generated by running the legacy
   ``render/pens.py`` at commit 14f1960 over one fixed sample. A re-derived formula fails even
   if it looks right, and a mistranscription cannot hide behind a matching restatement.
2. **The formula restated.** Each expression is spelled out again from the legacy source in the
   assertion, so a wrong *literal* is caught too.

Exact equality throughout, never ``pytest.approx``: the differential oracle compares SHA-256 of
formatted floats, so "close enough" is the wrong tolerance for this module.
"""

from __future__ import annotations

import math

import pytest
from hypothesis import given
from hypothesis import strategies as st

from rmspec.domain.models import PenType, Point
from rmspec.render import _pens
from rmspec.render._pens import (
    BallpointModel,
    CalligraphyModel,
    EraserModel,
    FinelinerModel,
    HighlighterModel,
    MarkerModel,
    MechanicalPencilModel,
    PaintbrushModel,
    PencilModel,
    SegmentInput,
    ShaderModel,
    direction_to_tilt,
    model_for,
    profile_for,
)

BASE_WIDTH = 2.0
BLUE = (78, 105, 201)
SAMPLE = SegmentInput(speed=100, direction=50, width=200, pressure=128, last_width=1.5)

#: ``(width, colour, opacity)`` for :data:`SAMPLE`, produced by the legacy renderers.
_LEGACY_SEGMENT: dict[str, tuple[float, tuple[int, int, int], float]] = {
    "Fineliner": (2.0, BLUE, 1.0),
    "Ballpoint": (50.751960784313724, (70, 94, 180), 1.0),
    "Marker": (44.706481037140264, BLUE, 1.0),
    "Pencil": (64.92082994579764, BLUE, 0.8505882352941176),
    "MechanicalPencil": (2.0, BLUE, 0.8007843137254902),
    "Paintbrush": (58.81487943970335, BLUE, 1.0),
    "Calligraphy": (25.11602032807943, BLUE, 1.0),
    "Highlighter": (15.0, BLUE, 0.3),
    "Shader": (12.0, BLUE, 0.1),
    "Eraser": (2.0, (255, 255, 255), 1.0),
}

_MODELS = {
    "Fineliner": FinelinerModel(BASE_WIDTH),
    "Ballpoint": BallpointModel(BASE_WIDTH),
    "Marker": MarkerModel(BASE_WIDTH),
    "Pencil": PencilModel(BASE_WIDTH),
    "MechanicalPencil": MechanicalPencilModel(BASE_WIDTH),
    "Paintbrush": PaintbrushModel(BASE_WIDTH),
    "Calligraphy": CalligraphyModel(BASE_WIDTH),
    "Highlighter": HighlighterModel(BASE_WIDTH),
    "Shader": ShaderModel(BASE_WIDTH),
    "Eraser": EraserModel(BASE_WIDTH),
}


@pytest.mark.parametrize("name", sorted(_LEGACY_SEGMENT))
def test_every_model_reproduces_the_legacy_segment(name: str) -> None:
    model = _MODELS[name]
    width, colour, opacity = _LEGACY_SEGMENT[name]
    assert model.segment_width(SAMPLE) == width
    assert model.segment_color(SAMPLE, BLUE) == colour
    assert model.segment_opacity(SAMPLE) == opacity


def test_ballpoint_width_matches_the_legacy_expression() -> None:
    expected = (0.5 + 128 / 255) + (200 / 4) - 0.5 * (100 / 4 / 50)
    assert BallpointModel(BASE_WIDTH).segment_width(SAMPLE) == expected


def test_marker_width_matches_the_legacy_expression() -> None:
    tilt = 50 * (math.pi * 2) / 255
    expected = 0.9 * ((200 / 4) - 0.4 * tilt) + 0.1 * 1.5
    assert MarkerModel(BASE_WIDTH).segment_width(SAMPLE) == expected


def test_pencil_width_matches_the_legacy_expression() -> None:
    tilt = 50 * (math.pi * 2) / 255
    expected = 0.7 * (
        ((0.8 * BASE_WIDTH) + (0.5 * 128 / 255)) * (200 / 4) - 0.5 * math.sqrt(tilt) + 0.5 * 1.5
    )
    assert PencilModel(BASE_WIDTH).segment_width(SAMPLE) == expected


def test_paintbrush_width_matches_the_legacy_expression() -> None:
    tilt = 50 * (math.pi * 2) / 255
    expected = 0.7 * (((1 + 1.4 * 128 / 255) * (200 / 4)) - 0.5 * tilt - 100 / 4 / 50)
    assert PaintbrushModel(BASE_WIDTH).segment_width(SAMPLE) == expected


def test_calligraphy_width_matches_the_legacy_expression() -> None:
    tilt = 50 * (math.pi * 2) / 255
    expected = 0.5 * ((0.5 + 128 / 255) * (200 / 4) - 0.5 * tilt + 0.5 * 1.5)
    assert CalligraphyModel(BASE_WIDTH).segment_width(SAMPLE) == expected


def test_pencil_opacity_is_exactly_one_at_full_pressure() -> None:
    """Full pressure lands on ``1.0``, so no ``opacity`` attribute is written at all."""
    full = SegmentInput(speed=0, direction=0, width=0, pressure=255, last_width=0.0)
    assert PencilModel(BASE_WIDTH).segment_opacity(full) == 1.0
    assert MechanicalPencilModel(BASE_WIDTH).segment_opacity(full) == 1.0


def test_ballpoint_leaves_ink_untouched_at_full_pressure() -> None:
    """``intensity`` reaches exactly ``1.0``, and ``int()`` truncation is a no-op there."""
    full = SegmentInput(speed=0, direction=0, width=0, pressure=255, last_width=0.0)
    assert BallpointModel(BASE_WIDTH).segment_color(full, BLUE) == BLUE


def test_ballpoint_truncates_rather_than_rounds_at_zero_pressure() -> None:
    none = SegmentInput(speed=0, direction=0, width=0, pressure=0, last_width=0.0)
    assert BallpointModel(BASE_WIDTH).segment_color(none, BLUE) == (62, 84, 160)


@pytest.mark.parametrize(
    ("direction", "expected"),
    [(0, 0.0), (128, 3.1539126247803413), (255, 6.283185307179586)],
)
def test_direction_to_tilt_boundaries(direction: int, expected: float) -> None:
    assert direction_to_tilt(direction) == expected


@pytest.mark.parametrize("direction", range(256))
def test_direction_to_tilt_agrees_with_the_domain_property(direction: int) -> None:
    """Two spellings of one conversion, pinned together so neither can drift alone."""
    sample = Point(x=0.0, y=0.0, direction=direction)
    assert direction_to_tilt(direction) == sample.direction_radians


@given(direction=st.integers(min_value=0, max_value=255))
def test_direction_to_tilt_stays_within_one_turn(direction: int) -> None:
    tilt = direction_to_tilt(direction)
    assert 0.0 <= tilt <= math.pi * 2


@given(
    speed=st.integers(min_value=0, max_value=65535),
    direction=st.integers(min_value=0, max_value=255),
    width=st.integers(min_value=0, max_value=65535),
    pressure=st.integers(min_value=0, max_value=255),
    last_width=st.floats(min_value=0.0, max_value=100.0),
)
def test_every_model_returns_a_finite_width_for_any_wire_sample(
    speed: int,
    direction: int,
    width: int,
    pressure: int,
    last_width: float,
) -> None:
    """No channel a stylus can produce makes a formula raise or return a NaN."""
    sample = SegmentInput(
        speed=speed,
        direction=direction,
        width=width,
        pressure=pressure,
        last_width=last_width,
    )
    for model in _MODELS.values():
        assert math.isfinite(model.segment_width(sample))
        assert 0.0 <= model.segment_opacity(sample) <= 1.0


@given(pressure=st.integers(min_value=0, max_value=255))
def test_pencil_opacity_rises_with_pressure(pressure: int) -> None:
    sample = SegmentInput(speed=0, direction=0, width=0, pressure=pressure, last_width=0.0)
    assert PencilModel(BASE_WIDTH).segment_opacity(sample) == 0.7 + 0.3 * (pressure / 255)


THICKNESS = 3.0

#: Every canonical pen and the base width and linecap the legacy ``Pen.from_stroke`` gave it.
_PROFILE_TABLE = [
    (PenType.FINELINER_1, THICKNESS * 1.8, "round"),
    (PenType.BALLPOINT_1, THICKNESS, "round"),
    (PenType.MARKER_1, THICKNESS, "round"),
    (PenType.PENCIL_1, THICKNESS, "round"),
    (PenType.MECHANICAL_PENCIL_1, THICKNESS**2, "round"),
    (PenType.PAINTBRUSH_1, THICKNESS, "round"),
    (PenType.CALLIGRAPHY, THICKNESS, "round"),
    (PenType.HIGHLIGHTER_1, 15.0, "square"),
    (PenType.SHADER, 12.0, "round"),
    (PenType.ERASER, THICKNESS * 2, "square"),
    (PenType.ERASER_AREA, THICKNESS, "square"),
]


@pytest.mark.parametrize(("pen", "base_width", "linecap"), _PROFILE_TABLE)
def test_profile_table_reproduces_the_legacy_arms(
    pen: PenType,
    base_width: float,
    linecap: str,
) -> None:
    profile = profile_for(pen, stroke_thickness=THICKNESS)
    assert profile is not None
    assert profile.base_width == base_width
    assert profile.stroke_linecap == linecap


@pytest.mark.parametrize("pen", list(PenType))
def test_every_pen_has_a_profile_and_a_model(pen: PenType) -> None:
    """Exhaustiveness. Adding a ``PenType`` without physics fails here, not silently."""
    profile = profile_for(pen, stroke_thickness=THICKNESS)
    assert profile is not None, f"{pen.name} has no width rule"
    assert model_for(pen, base_width=profile.base_width) is not None, f"{pen.name} has no model"


@pytest.mark.parametrize("pen", list(PenType))
def test_a_toolbar_row_two_pen_renders_as_its_row_one_twin(pen: PenType) -> None:
    canonical = profile_for(pen.canonical, stroke_thickness=THICKNESS)
    folded = profile_for(pen, stroke_thickness=THICKNESS)
    assert folded == canonical


def test_profile_for_reports_a_pen_it_has_no_rule_for(monkeypatch: pytest.MonkeyPatch) -> None:
    """The loud-failure path, reached by dropping a table entry.

    A ``PenType`` outside the enum is unconstructable and every member has a rule, so this is
    the only way to exercise the ``None`` branch -- which is exactly why the exhaustiveness
    test above is what actually guards it.
    """
    table = dict(_pens._PROFILES)
    del table[PenType.SHADER]
    monkeypatch.setattr(_pens, "_PROFILES", table)
    assert profile_for(PenType.SHADER, stroke_thickness=THICKNESS) is None


def test_model_for_reports_a_pen_it_has_no_model_for(monkeypatch: pytest.MonkeyPatch) -> None:
    table = dict(_pens._MODELS)
    del table[PenType.SHADER]
    monkeypatch.setattr(_pens, "_MODELS", table)
    assert model_for(PenType.SHADER, base_width=1.0) is None
