"""``rmspec --skill``: the one hand-written document an agent should read before it calls.

Three documents describe this CLI and they are not interchangeable. ``rmspec manifest`` is the
surface, generated by introspection. ``AGENTS.md`` is that manifest rendered as prose, generated
too, so it cannot contradict the code. ``SKILL.md`` -- printed by this module -- is the third,
and it is the only one written by hand, because what it carries cannot be introspected: which
operations a *person* performs on the tablet and which a caller performs on the host, which two
commands are irreversible and must be confirmed first, and what a reader should deliberately not
learn.

Why a flag rather than a command
--------------------------------
``--skill`` sits beside ``--help`` and ``--version`` and is registered the same way cyclopts
registers those: a command whose name begins with two dashes. It is then dropped from the
manifest's ``commands`` list by :func:`rmspec.cli._manifest._registrations`, exactly as the other
two are, because that list means "operations a caller can perform" and this performs none. The
pointer to it is a field of its own in the manifest instead -- see :func:`describe_skill`, whose
result is the first thing a first-contact agent reads.

Why the digest exists
---------------------
An agent that has read this document once should not have to read it every session, and an agent
that cached it needs to know when the cache is stale. The manifest carries a digest of the exact
bytes ``--skill`` prints, so a caller compares one short string instead of re-reading a document
or trusting a version number that moves for unrelated reasons.

Why the file is Markdown beside the code
----------------------------------------
It ships inside the wheel and is read with :mod:`importlib.resources`, which is what lets an
installed ``rmspec`` print it with no repository present. Keeping it a real ``.md`` file rather
than a string constant is deliberate: it is a document that people edit and review as a document,
and ``uv_build`` already includes non-Python files that sit in the module directory -- ``py.typed``
proves the path.

What keeps it honest
--------------------
It is prose, so no generator can guarantee it. ``test_cli_skill.py`` gates the half that *can* be
checked: every ``rmspec <verb>`` and every ``--flag`` the document names must exist in the
manifest. That catches the failure that actually costs a reader something -- being told to run
what is not there -- without pretending the judgement is derived. The document says so about
itself in its own second paragraph, so a reader is never misled about which kind of document it
is holding.
"""

from __future__ import annotations

import hashlib
import sys
from importlib import resources
from typing import Final

__all__ = [
    "SKILL_COMMAND",
    "SKILL_FLAGS",
    "SKILL_RESOURCE",
    "SKILL_SUMMARY",
    "describe_skill",
    "digest",
    "read",
    "skill",
]

SKILL_RESOURCE: Final = "SKILL.md"
"""The document's filename inside this package, and the only place it is spelled."""

SKILL_FLAGS: Final = ("--skill",)
"""The invocation, as a tuple for the same reason ``App.help_flags`` is one.

:func:`rmspec.cli._manifest._registrations` unions this with cyclopts' own ``help_flags`` and
``version_flags`` to decide what is a pseudo-command rather than an operation. A tuple rather
than a bare string so adding a second spelling stays a one-line change there.
"""

SKILL_COMMAND: Final = f"rmspec {SKILL_FLAGS[0]}"
"""How a caller asks for the document, as the manifest publishes it.

Composed rather than written out, so the string an agent is told to run and the flag that runs
it cannot disagree.
"""

SKILL_SUMMARY: Final = (
    "How to use this CLI, what a person can do on the tablet, and what you can do."
)
"""One line, for a caller deciding whether to spend the tokens on the document itself."""

_DIGEST_PREFIX: Final = "sha256:"
"""Names the algorithm in the digest, so a reader never has to guess which one produced it."""


def read() -> str:
    """Return the document's exact text.

    Returns
    -------
    str
        The bytes of :data:`SKILL_RESOURCE`, decoded as UTF-8. Read from the installed package
        rather than from a path, so an ``rmspec`` installed as a tool prints it with no
        repository anywhere on the machine.
    """
    return resources.files(__package__).joinpath(SKILL_RESOURCE).read_text(encoding="utf-8")


def digest() -> str:
    """Return a digest of the document, for a caller that cached it.

    Returns
    -------
    str
        ``sha256:`` followed by the hex digest of the exact bytes :func:`read` returns. Of the
        document and nothing else: not the version, which moves when unrelated code changes, and
        not a timestamp, which moves when nothing changes at all.
    """
    payload = read().encode("utf-8")
    return f"{_DIGEST_PREFIX}{hashlib.sha256(payload).hexdigest()}"


def describe_skill() -> dict[str, str]:
    """Describe the document for the manifest, without including it.

    Returns
    -------
    dict[str, str]
        ``command``, ``summary`` and ``digest``. The manifest carries the pointer rather than the
        prose because the two have different readers: a caller parses the manifest and *reads*
        the skill, and folding several kilobytes of Markdown into a JSON payload would make every
        machine consumer pay for a document written for a different audience.
    """
    return {
        "command": SKILL_COMMAND,
        "summary": SKILL_SUMMARY,
        "digest": digest(),
    }


def skill() -> int:
    """Print the guide to using this CLI, for a human or an agent meeting it for the first time.

    Returns
    -------
    int
        ``0``. Reading a file that ships inside this package cannot fail against an ``rmspec``
        that imported at all.

    Notes
    -----
    Raw Markdown on **stdout**, with no envelope and no ``--json`` flag. Every other command
    here reserves stdout for a parser and stderr for a person, and this obeys that rule rather
    than contradicting it: the document *is* the payload, its reader is whoever asked, and
    wrapping prose in ``{"api_version": ..., "data": ...}`` would make an agent unpack a string
    to read a paragraph. It is the same choice ``--version`` makes for the same reason.
    """
    sys.stdout.write(read())
    return 0
